ETLCPP/etl

imap.h, map.h, map_base.h, test/codeblocks/ETL.cbp, test/codeblocks/ETL.depend, test/codeblocks/ETL.layout, test/iar/etl.dep, test/iar/etl.ewp, test/iar/etl.ewt, test/keil/Test1.uvoptx, test/keil/Test1.uvprojx, test/test_map.cpp, test/vs2013/etl.vcxproj, test/vs2013/etl.vcxproj.filters
John,
Here is the first etl::map implementation without the balance algorithms.
=> initial release of etl::map without balance

imap.h, test/test_map.cpp, test/test_set.cpp
Here are the test_map/test_set fixes that appear to allow codeblocks to compile under gcc.
=> gcc compiler fixes for codeblocks

.gitmodules
You accidentally used a local path in the git submodule file. I fixed it to point to the proper GitHub repository.
=> Fix unittest-cpp submodule link

src/exception.h
Hi John, seems that there was a missing few changes in the exception.h file after you built support for the strict options in your last commit.
=> Fixed missing changes to support strict builds.

src/flat_map.h, src/forward_list.h, src/intrusive_forward_list.h, src/intrusive_list.h, src/list.h, src/reference_flat_map.h
fixes some -Wundef errors when _DEBUG was not defined
=> replace usages of _DEBUG with ETL_DEBUG

src/multimap.h
Compiling a source that includes `multimap.h` with `-Wextra` flag issues the following warning:
```
multimap.h: In member function ‘void etl::multimap_base::rotate_3node(etl::multimap_base::Node*&, uint_least8_t, uint_least8_t)’:
multimap.h:361:75: warning: enumeral and non-enumeral type in conditional expression [-Wextra]
position->children[dir]->weight = third != kNeither && third != dir ? dir : kNeither;
^
```
This warning can be fixed by casting the enum correctly.
=> Cast enum in multimap.h correctly

src/variant.h
Fixes warnings that are issued by `clang++3.8` when compiling a source which includes `variant.h`, with `-Wall` and `-Wextra` warnings enabled.
=> Remove unused variables in variant.h

LICENSE
GitHub uses the [licensee](https://github.com/benbalter/licensee) ruby gem to detect the license type of the repository. licensee [uses](https://github.com/benbalter/licensee/blob/master/docs/what-we-look-at.md#known-licenses) the license texts from [choosealicense.com](https://choosealicense.com/) so if the text of your license file differs from their license it will not be recognized. GitHub allows [filtering searches by license type](https://blog.github.com/2017-11-03-search-repositories-by-license/) and also shows the license type on the homepage of your repository and when viewing the license page but these features are only available when the license is recognized.
=> Fix license formatting so it will be recognized

include/etl/unordered_map.h, include/etl/unordered_multimap.h, include/etl/unordered_set.h
1. Fixes extra semicolon warnings
2. Suppresses unused parameter warnings
3. Fixes unused variable warnings
=> Fix clang warnings on etl::unordered_map, etl::unordered_multimap, and etl::unordered_set

include/etl/debug_count.h, include/etl/deque.h, include/etl/flat_map.h, include/etl/flat_multimap.h, include/etl/flat_multiset.h, include/etl/flat_set.h, include/etl/forward_list.h, include/etl/list.h, include/etl/map.h, include/etl/multimap.h, include/etl/multiset.h, include/etl/private/vector_base.h, include/etl/queue.h, include/etl/set.h, include/etl/stack.h, include/etl/unordered_map.h, include/etl/unordered_multimap.h, include/etl/unordered_multiset.h, include/etl/unordered_set.h, include/etl/vector.h
clang++ emits `-Wextra-semi` warnings if *DEBUG_COUNT is undefined.
=> Add semicolon to DEBUG_COUNT definitions to fix clang extra semicolon warnings

include/etl/list.h
Overlooked during https://github.com/ETLCPP/etl/pull/89, sorry.
=> Fix extra semicolon warning in list.h

include/etl/atomic/atomic_std.h
There is small hotfix removing extra semicolon after namespace etl in atomic_std.h
=> atomic_std: removed extra ';' semicolon after namespace

library.json
This is a WIP PR related to discussion at #121 and should not be merged as such. If you use labels, please add a "WIP" label on this one.
After some fiddling I managed to create a suitable `library.json` file based on instructions here: https://docs.platformio.org/en/latest/librarymanager/config.html
I mapped the values in `library.properties` to best matching fields. There's bunch of other fields you would likely want to add like `keywords`, `export` (to filter out folders like `temp`), `examples` (to possibly add only some of the examples). Also I know ETL isn't Arduino specific and it'd likely work for other platforms also, I added only the ones I have now confirmed working.
I am able to compile the QueuedMessageRouter example with this `platformio.ini` configuration:
```ini …
```
=> PlatformIO support (WIP)

library.json
This updates `library.json` with info I found from `conanfile.py` and adds platforms `atmelavr` and `ststm32`. Arduino cores for both Espressif platforms `espressif8266` and `espressif32` include STL so they were easy to get working. AVR core required adding [ArduinoSTL](https://github.com/mike-matera/ArduinoSTL) as a library dependency and STM32 core (stm32duino) required a (modified fork)[https://github.com/cparata/ArduinoSTL.git] of the same library.
I experimented a with different `etl_profile.h` macros and the main observation was that  `#define ETL_CPP11_SUPPORTED 1` compiled only on the Espressif platforms. All platforms use either `-std=c++11` or `-std=gnu++11` build flag so I don't know what that was about. I pretty much had no idea what I was doing but hopefully this helps push …
=> Improve initial PlatformIO support

conanfile.py
This completes #142 
```
git tag test_version
conan create .
```
You should see the version will be set to "test_version".
Additionally, if there is no tag for the current git HEAD, `conan create` will fail.
=> Allow conan's etl version metadata to automatically update via git tags

include/etl/stl/alternate/algorithm.h
This change worked for me on Arduino. See issue 166
=> copy algorithm overload fo POD types returned wrong iterator. Fix.

include/etl/cstring.h, include/etl/u16string.h, include/etl/u32string.h, include/etl/wstring.h
make_string utility function.
It provides possibility to safely create etl::string from string literal.
Example:
```
auto testString = etl::make_string("test567");
std::cout << "testString: " << testString.data() << std::endl;
std::cout << "testString: " << testString.max_size() << std::endl;
std::cout << "testString: " << testString.size() << std::endl;
```
Output:
```
testString: test567
testString: 7
testString: 7
```
=> Added utility function etl::make_string 

test/CMakeLists.txt
I had forgotten to add test_hsm.cpp to CMakeLists.txt so it was not included in the test. That might have caused some problems. Now I have added it and tested with gcc 5.3, 7.4 and 8.3 (latest for release 8 in Ubuntu) and all work fine without compilation errors when running the full test suite.
=> Added test_hsm.cpp to CMakeLists.txt

include/etl/memory.h
clang complains:
```
etl-src/include/etl/memory.h:309:119: warning: unused parameter 'count' [-Wunused-parameter]
TOutputIterator uninitialized_copy(TInputIterator i_begin, TInputIterator i_end, TOutputIterator o_begin, TCounter& count)
```
=> Add missing count calculation

meson.build
Tests are being built by default, which is desirable for the primary project but not for subprojects - primarily due to the increase in compilation time for the dependent project. This logic still allows the test binary to be built in a subproject, but now it must be manually requested by the user.
=> Meson build improvement: Don't build tests by default if used as a subproject

include/etl/optional.h, include/etl/queue.h
Both optional and queue used std::move without checking
ETL_NOT_USING_STL. Both usages can simply use etl::move
instead.
=> Use etl::move instead of std::move

include/etl/span.h, test/CMakeLists.txt, test/test_span.cpp
Fixes #234
Correct handling when count equals dynamic_extent,
which would previously cause the end pointer to be set to the
wrong location.
=> Fix span dynamic extent

include/etl/error_handler.h
Fixing C++98/C++03 compatibility issues with error_handler.h by using `typedef` instead of C++11 type aliases.
=> error_handler.h: Change C++11 type aliases to typedefs

include/etl/type_traits.h
https://stackoverflow.com/questions/48225673/why-is-stdis-pod-deprecated-in-c20
=> std::is_pod is deprecated in C++20

.github/workflows/main.yml
Multi Ubuntu build and artifacts archiving
Build only on Ubuntu 18.04 and 20.04
Ubuntu 16.04 does not support C++17
=> Mulit Ubuntu build and artifacts archiving (#2)

include/etl/bitset.h
Fix typo in comment for parameter name
=> Fix comment for parameter name

.github/workflows/main.yml
Each "run:" call gets a new environment.
With this, the first "run:" is exporting CC and CXX.
In this "run:" the cmake stuff is created.
The next "run:" to make, is using the default CC and CXX, which is
GCC instead of clang.
And then some of the stuff is build with clang other with gcc
* moved cmake, make and running tests in one "run:" command, so they
are sharing the same environment
* fixed indention
* renamed the name to Build and run
* Build build-clang-9-Linux and build-clang-10-osx are similar now.
=> cmake and make using same env with CC and CXX

include/etl/array.h, include/etl/array_view.h
Add template deduction guides (C++17) for array and array_view. This will allow something like this to compile:
```
etl::array arr{0, 1, 2, 3, 4, 5);
etl::array_view arr_view1{arr};
etl::array_view arr_view2{arr.begin(), arr.end()};
etl::array_view arr_view3{arr.begin(), 2};
etl::array_view arr_view4{arr_view1};
uint8_t c_array[5] = {0};
etl::array_view arr_view5{c_array};
```
=> Add template deduction guides for array and array_view

include/etl/list.h
The `etl::list` class has a missing overload of `rend() const` causing unwarranted compile errors.
=> Add missing `rend() const` to list.h

include/etl/error_handler.h, include/etl/list.h, test/codeblocks/ETL.cbp
The list::full method asserts for lists with max size equal to zero.
=> etl::list<int, 0>::full() asserts

include/etl/list.h
Prevent zero sized `list<int, 0> x;` from always asserting.
=> Fix faulty assert in `list<int,0>::available`

include/etl/bip_buffer_spsc_atomic.h
This is a blueprint for a single producer single consumer bi-partite buffer implementation, which is very beneficial to have in embedded context as it provides a DMA-friendly quasi-circular buffer. This branch is certainly not ready for merging, I just wanted to get the ball rolling to get this feature in. So let's discuss how to implement this properly. E.g. it's currently using array_view with mutable option, which should most likely be replaced.
Based on the works of Andrea Lattuada and James Munns:
https://blog.systems.ethz.ch/blog/2019/the-design-and-implementation-of-a-lock-free-ring-buffer-with-contiguous-reservations.html
Whose design was inspired by Simon Cooke:
https://www.codeproject.com/Articles/3479/The-Bip-Buffer-The-Circular-Buffer-with-a-Twist
=> introduce bip buffer spsc atomic

include/etl/algorithm.h, test/test_algorithm.cpp
This adds an overload for etl::equal that takes (begin,end,begin,end) 4 parameters just like std::equal does since C++14.
=> add overload for etl::equal that compares lengths

include/etl/span.h, test/test_span.cpp
fix for #316 
make etl implementation of std::span more compliant with the standard implementation:
- add missing overloads for etl::span::first and etl::span::last
- remove explicit from some conversion constructors to allow implict conversion during assignment
=> Make span std compliant

CMakeLists.txt
Gcc doesn't apply warning to system includes paths. This change
allows a project to use high warning levels without getting swamped by ETL
issues.
=> Export headers as system includes

include/etl/type_traits.h
Stop the compiler warning about type conversion from ```unsigned long``` to ```unsigned int```, and use the same type as std::extent.
https://en.cppreference.com/w/cpp/types/extent
=> Fix extent type conversion warning

include/etl/buffer_descriptors.h, include/etl/multi_range.h
Gives problem in C++98/03 mode.
=> Correct use of ETL_NULLPTR instead for keyword nulllptr

include/etl/state_chart.h
It's the only file to include internal header files with "etl/... .h".
=> Remove etl/ prefix in state_chart.h

include/etl/string_utilities.h
Lacks `<ctype.h>` (deprecated in C++98 and forward) or <cctype> (prefered, since `<cctype>` is not part of the STL. This would give reason to use `std::toupper/tolower` instead of `::toupper/tolower`.
If `#include <etl/string_utilities.h>` is included before `<etl/string.h>` then this happens:
```
Then In file included from .../etl/t.m.cpp:1:
.../etl/include/etl/string_utilities.h: In function ‘void etl::to_upper_case(TString&)’:
.../etl/include/etl/string_utilities.h:809:53: error: ‘::toupper’ has not been declared
809 |     etl::transform(s.begin(), s.end(), s.begin(), ::toupper);
|                                                     ^~~~~~~
.../etl/include/etl/string_utilities.h: In function ‘void etl::to_lower_case(TString&)’:
.../etl/include/etl/string_utilities.h:818:53: error: …
```
=> string_utilities.h failes to compile with NO_ETL_STL

include/etl/delegate.h, test/test_delegate.cpp
Currently, it is not possible to forward parameters that can't be copied but only moved as parameter to a delegate call.
Therefore, I suggest to use std::forward to enable this feature. #357
=> Add moveable parameter support to delegate

include/etl/algorithm.h, include/etl/map.h, include/etl/private/pvoidvector.h
=> Delete the superfluous ;

CMakeLists.txt
This PR enables installation of the library, by adding a "make install" option.  It also installs a cmake config file so the library can be consumed by applications using the standard cmake ```find_package(etl)``` approach
```
mkdir build
cmake -DCMAKE_INSTALL_PREFIX=~/some_directory ..
make install
```
=> Add "make install" option

include/etl/fsm.h, include/etl/generators/fsm_generator.h, include/etl/hfsm.h, meson.build, test/CMakeLists.txt, test/test_hfsm.cpp
This adds the hierarchical state machine capabilities as an inherited class to the already existing FSM.
The states needed modification to add pointers to the parent and child states in the FSM, as well as a check to call the parent if it exists.
In order to work properly, states with no change need to return `ifsm_state::NO_CHANGE` rather than their given state id.
Otherwise, when an event isn't handled, it will return the parent state rather than the active state.
Also, in this implementation, a state cannot return a different state during the `on_enter_state()` function, as it would cause complexity with the enters and exits through the hierarchy.  An assert has been added to check for that.
=> Add hierarchical FSM capabilities to the FSM.

include/etl/priority_queue.h, include/etl/queue.h, include/etl/stack.h
In my project I'm trying to pass `etl::queue` to a library function that expects a "queue-like" container. The library is expecting `etl::queue` to have a type defintion for `container_type`, just like `std::queue` - and the compilation fails with the error 
```
no type named 'container_type' in 'etl::queue
```
Adding this typedef to the `etl::queue` class solves the issue, and the class is more in-line with `std::queue`.
=> Add container_type type definition to etl::queue to better match std::queue

include/etl/optional.h
The constructors of etl::optional with no argument or with etl::nullopt_t
argument do not initalise the storage data member. When compiling with
gcc with some specific optimisation levels, this can generate a
-Wmaybe-uninitialized diagnostic warning.
Resolves #380
=> Fix uninitialised warning in etl::optional

include/etl/debounce.h
Currently these state tables are being defined in the data section of RAM. As these tables are unchanged, this change allows them to be placed in the text section instead. As they are function local objects, they also get lazy initialized causing references to the dynamic shared object which are unnecessary. This PR marks these tables as `ETL_CONSTANT` which should work for all C++ versions. I believe no new tests should be necessary as the functionality is the same.
=> Change debounce state tables to be defined as constant

include/etl/limits.h, include/etl/profiles/determine_compiler.h
When using clang to cross-compile to AVR this error arises:
```
[build] include/etl/limits.h:340:49: error: use of undeclared identifier '__WCHAR_MIN__'
[build]     static ETL_CONSTEXPR wchar_t min() { return WCHAR_MIN; }
[build]                                                 ^
[build] /usr/lib/avr/include/stdint.h:602:19: note: expanded from macro 'WCHAR_MIN'
[build] #define WCHAR_MIN __WCHAR_MIN__
```
Unlike gcc (avr-gcc), clang does not define `__WCHAR_MIN__`.
This can be verified by running this command:
`clang -dM -E --target=avr - </dev/null | grep WCHAR`
**Note: you need a clang version that supports AVR, I believe from clang 12 onwards the AVR architecture is supported out of the box.**
The above command will produce this output:
```
clang-11: warning: no target microcontroller …
```
=> Define missing macro when cross-compiling with clang

arduino/examples/Vector_Examples/Example_Vector_1_simple_use/Example_Vector_1_simple_use.ino
Fix issue #399 by defining the ```ETL_NO_STL``` macro in the vector container arduino example. Without this, the sketch does not compile for Arduino Uno.
=> Fix traits error for arduino examples

include/etl/message.h
added a 2nd template parameter to etl::message in order to specify a base class different to etl::imessage.
Custom base class is still required to inherit from etl::imessage.
=> added optional template parameter to etl::imessage (#384)

include/etl/bip_buffer_spsc_atomic.h
With these commits I'm addressing the raised point from #402:
> I noticed that clearing or destructing the buffer does not call the destructors for the buffered items. Was this bip buffer only intended for trivially destructible types?
Now the buffer's `clear()` calls the destructors of the buffered items: 780fe8c and the buffer's destructor calls clear(): 01f8629
> Also, the top level template class does not define copy/move constructors or assignment operators. Should these be marked as disabled?
The top level template class doesn't know of the stored type, so copying that would be fine I guess. This is the same situation as in queue_spsc_atomic_base, so it would only make sense to apply the same convention on both types.
I've also fixed a regression so the tests can be built again: …
=> Feature/bip buffer spsc atomic (#402 follow-up)

include/etl/queue_spsc_atomic.h, test/test_queue_spsc_atomic.cpp
This adds a `peek` method to the `queue_spsc_atomic` container. Peek is the same as pop except the queue is not modified by this operation. There is no need for a `void` peek as that would essentially be a no operation. If this pattern looks good, let me know if we should more broadly apply it to the other queue classes. I wanted to wait for feedback before putting that effort in.
I also wasn't sure if I should use the `front` naming convention or not. I also am not sure if this should be returning a reference or copying into a reference argument as I have it. I have one question about move semantics which I've posted inline to the code review.
In general, I'm not 100% sure about the direction and code in this PR, and would consider it more of a starting point for a conversation.
=> Add peek to queue_spsc_atomic

.clang-format
I did a partial formating of new code by this configuration see [here](https://github.com/ETLCPP/etl/pull/433/commits/e5f38f3d2270169f7275bf908e289b06195f084f)
=> initial version of a clang format file that matches quite good with the existing code style

include/etl/ipool.h
When doing two allocations from the pool in a row, clang-tidy complains that line 359 is a `nullptr` dereference due to the `!=` operator and some erroneous assumptions as to the value of `items_allocated`.
Changing the `!=` to a `<` results in this error going away and tests still pass.
=> Change != to < in ipool to get rid of erroneous clang-tidy nullptr dereference warning

include/etl/byte_stream.h
The two removed casts were causing warnings in IAR, since it was only adding const.  The calling function is already const, so it isn't necessary.
=> Remove unnecessary casts that causes warnings.

include/etl/map.h, include/etl/multimap.h, include/etl/multiset.h, include/etl/set.h, test/test_map.cpp, test/test_multimap.cpp, test/test_multiset.cpp, test/test_set.cpp
Beginning with C++11, erase(iterator) and erase(const_iterator) returns an iterator following the removed element.
This PR improves C++11 compatibility for the STL container replacements in etl by adding the missing return value.
I didn't touch the flat_* and reference_flat_* containers in etl because I'm not very familiar with them. If necessary, I could try to add the return value there as well.
=> let map/multimap/set/multiset return iterator on erase

include/etl/delegate.h
etl::delegate has a user-written copy constructor and a defaulted assignment
operator. The copy constructor does the same as a defaulted copy constructor,
therefore there is no need to add a user-written copy constructor.
The combination of user-written copy constructor and defaulted assignment
operator causes a warning in Coverity, a static code analyzer:
`copy_without_assign: Class etl::delegate<void ()> has a user-written copy constructor etl::delegate<void ()>::delegate(etl::delegate<void ()> const &) but no corresponding user-written assignment operator.`
This commit replaces the user-written copy constructor with a defaulted copy
constructor, which does the same.
=> harmonize copy ctor and assignment op for etl::delegate

include/etl/array.h, include/etl/basic_string.h, include/etl/forward_list.h, include/etl/list.h, include/etl/vector.h, test/test_list.cpp, test/test_vector.cpp
Beginning with C++11, most STL container modifier methods (like insert, emplace, erase, ...) accept a const_iterator instead of a iterator.
This PR improves C++11 compatibility for the STL container replacements in etl by accepting a const_iterator as argument. 
I didn't touch the flat_* and reference_flat_* containers in etl because I'm not very familiar with them. If necessary, I could try to add const_iterator there as well.
=> Const iterator for stl containers

include/etl/private/to_string_helper.h, test/test_to_string.cpp
=> Fix for double formatting with precision > 9

library.json
There is a conflict between the two library manifests: the field "name" differs. As result, PlatformIO Crawler fails and can't fetch the latest version. See 
https://registry.platformio.org/packages/libraries/etlcpp/Embedded%20Template%20Library
=> Sync library name with arduino version

library.json
The solution to https://github.com/ETLCPP/etl/pull/487
I propose to revert back a name to the original name https://registry.platformio.org/packages/libraries/etlcpp/Embedded%20Template%20Library
In any case, we still will have the issue. There is a `library.properties` manifest in the root of the repository which has the same manifest as https://github.com/ETLCPP/etl-arduino/blob/master/library.properties
Is it possible to REMOVE `library.properties` from the main repository? It does not make sense to keep it in the repository, the library in this form is not compatible with Arduino IDE. It will help us to avoid issues when 1 repo contains multiple manifests with the different names.
=> Revert back name to the original version, avoid conflict with arduino library

include/etl/bitset.h, include/etl/profiles/determine_compiler_language_support.h
Also defined ARDUINO as ETL_NO_CPP_NAN_SUPPORT
it does not have the functions nan, nanf or nanl, it does have `NAN` defined in `math.h` as
```C
#define NAN	__builtin_nan("")
```
was tested on arduino mega, I think the compiler is `avrisp` (I'm not that strong in arduino)
and visual studio 2020 defined to c++17
=> Added to_string, to_ulong and to_ullong to bitset

include/etl/char_traits.h, include/etl/endianness.h, include/etl/message_router.h, include/etl/private/delegate_cpp11.h
Fixes following greenhills compiler warnings
* etl/include/etl/message_router.h", line 2434 (col. 11): warning #111-D: statement is unreachable
* etl/include/etl/char_traits.h", line 105 (col. 19): warning #82-D: storage class is not first
=> Put storage class first and remove unreachable statement

include/etl/algorithm.h
clang complains about the line:
include/etl/algorithm.h:298:66: error: typedef 'value_type' locally defined but not used [-Werror=unused-local-typedefs]
typedef typename etl::iterator_traits<TIterator>::value_type value_type;
=> fix unused-local-typedefs warning

include/etl/platform.h
Hi!
A super minor issue I've faced.
Hope this helps.
Adjust the ETL variable type to match C++'s.
Macro __cplusplus is defined as a `long` as in:
- 199711L (C++98 or C++03)
- 201103L (C++11)
- 201402L (C++14)
- 201703L (C++17)
- 202002L (C++20)
It usually fits an int (4 bytes), but on some platforms (e.g. some Arduinos) an int is defined as a 2-bytes value.
=> Fix cplusplus constant type

README.md
Full set of CMake install instructions. Maybe this would be better situated on the ETL website (as well)?
Use of the major version requirement with `find_package` requires https://github.com/ETLCPP/etl/pull/523
=> CMake install instructions

include/etl/algorithm.h
Typedef for value_type is unused in the reverse function (pointers version), so it can be removed.
=> Remove unused typedef causing compilation warning.

CMakeLists.txt, README.md, cmake/GetGitRevisionDescription.cmake, cmake/helpers.cmake
Add ARGN  to `determine_version_with_git()` params list to allow specifying optional ALLOW_LOOKING_ABOVE_CMAKE_SOURCE_DIR flag.
=> CMake: add a flag to enable version lookup outside the root folder

CMakeLists.txt
The recently introduced changes made cross-compiling with cmake impossible.
From cmake docs:
New in version 3.14: If ARCH_INDEPENDENT is given, the installed package version will be considered compatible even if it was built for a different architecture than the requested architecture. Otherwise, an architecture check will be performed, and the package will be considered compatible only if the architecture matches exactly. For example, if the package is built for a 32-bit architecture, the package is only considered compatible if it is used on a 32-bit architecture, unless ARCH_INDEPENDENT is given, in which case the package is considered compatible on any architecture.
```
Note ARCH_INDEPENDENT is intended for header-only libraries or similar packages with no binaries.
```
=> cmake: write an arch independent version file

CMakeLists.txt, cmake/helpers.cmake
- Set library version from `version.txt` file if retrieval with `git describe` fails
- Add `FORCE` flag to `ETL_VERSION` CACHE entry. This would overwrite entries specified by the user but I think this is okay for this entry.
- Some more context information on the printout of the full version string
- New message prefix for all information messages printed out by the ETL `CMakeLists.txt`
=> Some CMake handling improvements

CMakeLists.txt
- This include was missing, so paths like `${CMAKE_INSTALL_DATAROOTDIR}` were not set properly. This is a problem if ETL is installed
=> added missing GNUInstallDirs include

CMakeLists.txt, README.md
When installing ETL with `find_package`, the actual import target is inside the `etl` namespace. This is the correction for the `CMake` instructions
=> New alias target etl::etl and CMake instructions update

include/etl/vector.h
changed copy by value in `resize()` to a `const_reference`
=> etl::vector unnecessay copy in constructor

include/etl/queue.h
Seems it was copied from stack implementation, but queue increments out
not, decrements it.
=> Fix comment in `queue::del_out`

include/etl/generators/type_traits_generator.h, include/etl/type_traits.h, test/test_type_traits.cpp
Discussion in #227 notes that a lack of implementation of `is_enum` prevents it from moving forward; not sure if it's because new type traits have been added since but I was able to implement `is_enum` by checking for `static_cast`ability into `int` with SFINAE, then ignoring other types that have this capability (arithmetic types, any class types with `operator int()` overloads, and reference types).
In the process I found that `is_reference` gave the wrong result for rvalue references, which this relies on, so I fixed that too.
Some other bugs which I noticed - I'll raise issues and submit PRs for these when I get the chance:
- `etl::void_t` suffers from a C++11 defect - see https://en.cppreference.com/w/cpp/types/void_t and search for CWG issue 1558
- The `message_parser` file has …
=> is_enum implementation

CMakeLists.txt, generator_test.py, include/etl/generators/message_router_generator.h
Partially fixes #564
I also wrote a script/test which can be used to verify as part of the build test process in the future that the generators match the actual headers, although in running it I found out that the `variant_pool.h` header is significantly out of sync. So, the test is left commented out in CMake (also, because I wasn't sure that was the best way to integrate a check like this into the build system).
=> Generator resync for message_router.h

CMakeLists.txt
I've been having the same problem as the user @jwellbelove mentioned in this comment: https://github.com/ETLCPP/etl/pull/340#issuecomment-804758033
I'm pretty sure it has to do with this bug in my version of GCC that automatically adds `extern "C"` to system headers for some targets.  
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=85211  
I added this option to give uses a way to opt out of treating these files like a system include without changing the default behavior.
=> Allow users to remove SYSTEM keyword because it forces C linkage for some gcc versions.

include/etl/private/delegate_cpp03.h, include/etl/private/delegate_cpp11.h
Enclose with parenthesis when invoking function pointers. This is useful when integrating with other libraries that has macros with the same name, resulting in conflict.
=> Invoke function pointers w/ parenthesis

include/etl/bip_buffer_spsc_atomic.h, test/test_bip_buffer_spsc_atomic.cpp
* improve the read reserve API by reserving all what's available by default
* add new write reserve API that allows prioritizing buffer space saving over getting large linear chunks
=> Bip buffer improvements

CMakeLists.txt
When defining the `target_include_directories` for the `INSTALL_INTERFACE`, `CMAKE_INSTALL_INCLUDEDIR` is used before it is defined by including the `GNUInstallDirs`. This means that the `INTERFACE_INCLDUE_DIRECTORIES` property of the installed target is actually empty. I moved up the `include(GNUInstallDirs)` line to fix that.
=> Fix include directory of installed target

include/etl/result.h, test/test_result.cpp
`etl::result<void>` was unusable due to the lack of a default constructor. This resulted 🙈 in the result being unusable as functions with `etl::result<void>` could only return errors results
=> Fix etl::result<void> being unusable due to deleted default constructor

include/etl/generators/message_packet_generator.h, include/etl/message_packet.h
IAR was tripping up on the syntax, generating warnings.  This addresses that per the discussion in #586
=> Fixed IAR build warnings in message_packet

include/etl/hash.h, test/test_hash.cpp
Should address #277 (and #147, which 227 is a duplicate of). 
Had to redefine the primary template for `etl::hash` I don't think there's a way to specialize for enums in general, without either introducing a dummy parameter in `etl::hash` for SFINAE or inheriting from a base class (which is what GCC and MSVC seem to do, when I glanced at their implementations). 
Tested with MSVC on Windows.
=> #227 Hash function for enums

include/etl/unordered_map.h, test/test_unordered_map.cpp
Allows user to provide a non-default-constructed `THash` and `TKeyEqual` to `unordered_map`. 
Similar changes could probably be made to the other `unordered_*` containers, but I only needed this change in `unordered_map`  in my application. 
While working on this I found a bug where `Key::operator==` gets used in `insert` instead of `key_equal_function`, which I've fixed as well.
Between this and #582, not sure if you want to take the opportunity to consider refactoring the `unordered_*` containers to share common code where possible.
=> Permit non-default-constructable hashes and key-equals in unordered_map

include/etl/string_utilities.h
Includes for minmax_push.h/minmax_pop.h are required due to usage of etl:min in this module. This prevents conflicts with system defined min/max macros.
=> Add minmax_push.h/minmax_pop.h includes

include/etl/placement_new.h
=> Workaround for __has_include(<...>) and ICCAVR.

include/etl/placement_new.h
This is related to #593 and #592.
This approach may be better as is uses the same syntax using `< ... >` as before. Has been suggested in https://github.com/ETLCPP/etl/pull/593#issuecomment-1239222424.
This is based on the insight, that the problem with IARCC occurs only in case the `__has_include` is used as part of a preprocessor definition. See https://github.com/ETLCPP/etl/pull/593#issuecomment-1239208693.
=> Use a different workaround for problems with IARCC.

include/etl/private/minmax_pop.h, include/etl/private/minmax_push.h
IAR C/C++ Compiler V6.70.1.929 for Atmel AVR does not support `push_macro` and does neither define macros for `min` or `max`.
This seems to be the same as #483 but for a different compiler.
=> Do not use min/max workaround for ICCAVR.

include/etl/platform.h
Macros must be defined before first include of stdint.h. Else they have no effect.
This relates to #591.
=> Move __STDC_LIMIT_MACROS and __STDC_CONSTANT_MACROS before stdint.h

test/test_fixed_iterator.cpp, test/test_hash.cpp, test/test_multi_array.cpp
Fix errors when trying to compile using g++ on mac os.
The errors were like this one : 
```
/Users/XXX/wip/2022/09/etl/test/test_array.cpp: In member function 'virtual void {anonymous}::Suitetest_array::Testtest_empty::RunImpl() const':
/Users/XXX/wip/2022/09/etl/test/test_array.cpp:309:24: error: 'data' may be used uninitialized [-Werror=maybe-uninitialized]
309 |       CHECK(!data.empty());
|                        ^
In file included from /Users/XXX/wip/2022/09/etl/test/test_array.cpp:33:
/Users/XXX/wip/2022/09/etl/test/../include/etl/array.h:313:24: note: by argument 1 of type 'const etl::array<int, 10>*' to 'constexpr bool etl::array<T, SIZE_>::empty() const [with T = int; long unsigned int SIZE_ = 10]' declared here
313 |     ETL_CONSTEXPR bool empty() const ETL_NOEXCEPT
| …
```
=> Fix 'maybe-uninitialized' g++ error on macos

include/etl/endianness.h
For for IAR compiler platform it is possible to automatically detect the native endianness.
References:
- [IAR C/C++ Development Guide Compiling and Linking for Arm Limited’s **Arm**® Cores](https://wwwfiles.iar.com/arm/webic/doc/ewarm_developmentguide.enu.pdf)
- [IAR C/C++ Compiler User Guide for Microchip Technology’s **AVR** Microcontroller Family](https://wwwfiles.iar.com/AVR/webic/doc/EWAVR_CompilerGuide.pdf)
=> Automatically detect native endianness for IAR compiler platform.

include/etl/unaligned_type.h
The storage type should either be always unsigned, or signed only when the template type is signed. The latter is implemented by this change, not necessarily in the nicest way, so do review first.
=> unaligned types: match the signedness of the storage type with the template type

include/etl/unordered_map.h, include/etl/unordered_multimap.h, include/etl/unordered_multiset.h, include/etl/unordered_set.h, test/test_unordered_map.cpp, test/test_unordered_multimap.cpp, test/test_unordered_multiset.cpp, test/test_unordered_set.cpp
Found some more places where `Key::operator==` or `Key::operator!=` were being used instead of `key_equal_function`; replaced them and added tests to demonstrate the previously bad behaviour.
=> [bug] Fix non-usages of key equal function

include/etl/hash.h, test/test_hash.cpp
Floating point numbers expressed in IEEE754 formats have separate bit-level representations for -0.0 and +0.0 (sign bit differs). so hashing (-0.0) and (+0.0) would've resulted in different hashes despite the two numbers comparing equal.
Note on other floating point cases:
- +/- infinity have consistent bitwise representation, so no special case needed there
- NaNs do not compare equal to each other (or to anything), so it's OK for the hash representations to be whatever
=> [bug] Special case check for hashing -0.0

test/CMakeLists.txt, test/UnitTest++/CMakeLists.txt
Make `UnitTest++` into its own CMake project. It includes the required libraries, keeping the `etl_tests` clean.
Using the `target_*` commands avoids `UnitTest++` to get defines which it doesn't need.
=> Provide cmake library for UnitTest++.

README.md, include/etl/observer.h, include/etl/platform.h, test/test_observer.cpp
This reverts commit fa7f6dc9d7187fb246af920b3c3dcfe75bdb7bbf.
The functionality removed in the previous commit was using the universal reference and was not a move parameter.  This is important to keep because it allows having values that are const and still using the nofity_observer pattern with them.  See [https://www.justsoftwaresolutions.co.uk/cplusplus/rvalue_references_and_perfect_forwarding.html](https://www.justsoftwaresolutions.co.uk/cplusplus/rvalue_references_and_perfect_forwarding.html) for a better explanation.
=> Revert "Fixed move parameter in notify_observers"

CMakeLists.txt
Currently if included in another project that enables the building tests with the standard option `BUILD_TESTS` the tests of ETL are also build and this cannot be changed from the parent project.
With this change it is possible to only build tests from the parent project.
=> Only build tests if top level project

include/etl/private/variant_legacy.h
For some definitions of `ETL_ASSERT()` there may be no return statement in case of an invalid type.
This results in undefined behavior.
> ```
> Warning[Pe940]: missing return statement at end of non-void function "etl::visit<TReturn,TVisitor,TVariant>(TVisitor &, TVariant const &) include\etl\private\variant_legacy.h 976
> ```
=> Avoid 'missing return statement at end of non-void function' in `etl::visit<>()`.

CMakeLists.txt, cmake/helpers.cmake
Different solution than proposed in the issue, since that proposed solution would given unexpected results when an intermediate (untagged) commit is checked out.
This change simply skips warning about a missing git version when this is a subproject, and uses the original version calculation logic.
I've also renamed `determine_version` to `determine_version_with_file`. I'd originally done this in an intermediate version of this PR, but I think that keeping the renaming is clearer code.
=> Don't warn on tag missing when subproject (#653)

include/etl/fsm.h, include/etl/generators/fsm_generator.h, include/etl/hfsm.h, test/test_hfsm.cpp
The FSM implementation of `start()` method only performs the first 'enter' if `call_on_enter_state` is set to `true`.  This can be problematic in the HFSM since the initial state might be hierarchal.  The same goes for `reset()` when the `call_on_exit_state` parameter is set to `true`.
This new implementation will service the 'enter' event for all states within the initial state's hierarchy (starting with the outermost parent state first and working all the way into the initial child state).
=> Added HFSM-specific start() and reset()

include/etl/basic_string.h
The comment for `\param s` didn't make sense here. Updated it to refer to `dest`, and mention the 'destination', not the 'source'.
=> Update a \param in basic_string.h

test/CMakeLists.txt
MinGW doesn't presently support sanitization.  So in order to support compiling unit tests in MinGW, a check has been added 
so that the sanitization options are only added if the compiler **isn't** MinGW.
=> Added sanitization fix for MinGW

include/etl/span.h, test/test_span_dynamic_extent.cpp, test/test_span_fixed_extent.cpp
These functions emulate the std C++20 functions std::as_bytes and std::as_writable_bytes.
I made an attempt to recreate 'as_bytes' and 'as_writable_bytes'. I have not any wider experience with metaprogrmaming, but I think this is correct.
=> feat(span): Add 'as_bytes' and 'as_writable_bytes'

include/etl/optional.h
Hi,
I've had compile issues with etl::optional after upgrading to version >= 20.35.13.
I think the cause was a missing forwarding reference in optional::storage::construct, hope this is correct.
Regards,
Manuel
=> fixed etl::optional emplace

include/etl/optional.h
Hi,
I propose to make `operator bool()` for `etl::optional` (POD specialization) explicit.
This would align it with the non-POD specialization and prevent some nasty bugs if one (like me) forgets to dereference an optional.
Regards,
Manuel
=> Optional(POD) operator bool explicit

include/etl/parameter_pack.h
Getting this error with `gcc (Ubuntu 10.3.0-1ubuntu1~20.04) 10.3.0` and `-std=c++17`
```
../subprojects/etl-20.36.1/include/etl/private/../parameter_pack.h:135:56: error: keyword ‘template’ not allowed in declarator-id [-Werror=pedantic]
135 |   constexpr size_t parameter_pack<TTypes...>::template index_of_type<T>::value;
```
Disclaimer: Not familiar with the `ETL_USING_CPPxx` macros intended usage.
=> parameter_pack: Fix C++17 pedantic build

include/etl/fsm.h
With `c++0x` a compiler error is generated due to missing class key in [fsm.h:L328](https://github.com/ETLCPP/etl/blob/ac236c9b98f999fbfc52b81cc854a755a1796a3d/include/etl/fsm.h#L328)
```
/path/to/etl-arduino-master/src/etl/fsm.h:309:5: error: a class-key must be used when declaring a friend
/path/to/etl-arduino-master/src/etl/fsm.h:309:5: error: friend declaration does not name a class or function
```
This PR adds `class` to avoid the compile issue.
=> fix missing class key with friend

include/etl/optional.h, test/test_optional.cpp
Fixes https://github.com/ETLCPP/etl/issues/714
=> optional::operator=(nullopt_t) sets valid to false

include/etl/array.h, include/etl/numeric.h
This is mainly usefull for creating constexpr arrays  in C++14 and up.
Example:
```c++
template <size_t SIZE>
constexpr etl::array<int, SIZE> x_squared(int start_x) {
etl::array<int, SIZE> out{};
etl::iota(out.begin(), out.end(), start_x);
for (int& elem : out) {
elem = elem * elem;
}
return out;
}
// Contains [25,16,9,4,1,0,1,4,9,16,25]
constexpr etl::array compile_time_array = x_squared<11>(-5);
// Contains [35,26,19,14,11,10,11,14,19,26,35]
constexpr etl::array lambda_generated_array = []() constexpr {
etl::array out{compile_time_array};
for (size_t i = 0; i < out.size(); ++i) {
out[i] = out[i] + 10;
}
return out;
}();
```
=> Allow manipulation of etl::array in constexpr function

include/etl/expected.h
Using `etl::expected` can be annoying below C++20 because constructors from `etl::unexpected` are always explicit.
Because of this it is not possible to use `return etl::unexpected()` in functions that return `etl::expected`.
This is my attempt at making the constructor conditionally explicit for C++11 and up.
=> Conditionally explicit etl::expected constructors that work in C++11

include/etl/optional.h
Hi,
I think the optional<pod> access operators are missing the "storage -> union -> T" part.
Regards,
Manuel
=> fixed optional access operators

include/etl/private/minmax_pop.h, include/etl/private/minmax_push.h
This pull request fixes a bug in the include mismatch detection of the minmax headers.
When using Green Hills, IAR or TASKING compiler the define 'ETL_PUSHED_MIN_MAX' is not set in 'minmax_push.h'. Therefore the include of 'minmax_pop.h' always leads to a compilation error (minmax_pop without matching push).
Related to #731 and 24272d99c093c01e195f4df3e4accd319c8530d1.
=> fix(minmax): fix bug in minmax include mismatch detection

include/etl/expected.h
Assignment operator of etl::expected form etl::unexpected attempts to save etl::unexpected to storage instead of the contained error.
=> Fix etl::expected assignment from etl::unexpected

include/etl/private/bitset_new.h
To get rid of the compiler warnings:
Warning[Pe111]: statement is unreachable
=> Remove some unreachable code in bitset_new.h

include/etl/multiset.h, include/etl/priority_queue.h, include/etl/set.h, test/test_deque.cpp, test/test_forward_list.cpp, test/test_indirect_vector.cpp, test/test_indirect_vector_external_buffer.cpp, test/test_list.cpp, test/test_map.cpp, test/test_multimap.cpp, test/test_multiset.cpp, test/test_priority_queue.cpp, test/test_set.cpp, test/test_unordered_map.cpp, test/test_unordered_multimap.cpp, test/test_unordered_multiset.cpp, test/test_unordered_set.cpp, test/test_vector.cpp, test/test_vector_pointer.cpp
The move assignment was not working properly for some container types if the target is not empty.
Affected container types: priority_queue, set, multiset.
Solution: clear() called in these move assignment functions before adding the new elements to the target container.
Unit tests modified for all containers types (even the ones that implemented the move assignment correctly) to prevent future regressions.
=> Fixed: move assignment not working for non-empty containers

include/etl/generators/message_packet_generator.h, include/etl/message_packet.h, include/etl/optional.h, include/etl/private/variant_legacy.h, include/etl/private/variant_variadic.h
We have a use-case, where we include etl-header relative (some wrapping stuff). This leads to problems when absolute paths are used. This PR changes those to relative paths; same as other "private" includes.
=> Make "private" includes relativ

CMakeLists.txt, include/etl/private/diagnostic_stringop_overread_push.h
moved BUILD_TESTS check outside of root cmake check to allow building tests when ETL is a submodule
added check for GNUC >= 11 for -Wstringop-overread ignore pragma since it isn't introduced until gcc/g++-11
=> Allow Building Tests as Submodule and GCC < 11

test/CMakeLists.txt
I observed that the GitHub Actions fail. Through analysis since which commit the build fails, I to applied a fix to make the workflow running successfully again.
I am not sure why this fixes the workflow. 🤷 I merely re-applied f208eb4073c98b3c190b17a73db3b61aa35fae25. I think that change accidentally got lost in the merge 95c7f44cc61d51406a70ccb9048724f9fbdd78f9.
=> Fix library error for Github Actions for Clang C++20

include/etl/set.h, include/etl/unordered_set.h, test/test_flat_set.cpp, test/test_reference_flat_set.cpp, test/test_set.cpp, test/test_unordered_set.cpp
When I tried to insert a value that was already in the set to a full set , it throws set_full error.
I believe it should let me try inserting an existing value. 
Resolves #783
=> Set is full error when adding existing item

include/etl/optional.h
Copy and move assignment only copy storage if assigned optional is valid.
=> Fix #832: Only copy/move storage value when optional is valid

include/etl/span.h
Potential fix for issue #842 
etl::span subspan function does not currently statically check extents. std::span does check this.
Code demonstration:
```
std::array<int, 10> array {0};
//std::span std_span1 = std::span(array).subspan<15, 1>(); //compile time error
//std::span std_span2 = std::span(array).subspan<5, 8>(); //compile time error
etl::span etl_span1 = etl::span(array).subspan<15, 1>(); //currently no compile time error
etl::span etl_span2 = etl::span(array).subspan<5, 8>(); //currently no compile time error
```
This PR should enable c++11 and newer to have compile error when the extent check fails.
=> In subspan function, add static checks on extents

cmake/GetGitRevisionDescription.cmake, examples/FunctionInterruptSimulation-Delegates/FunctionInterruptSimulation.cpp, examples/FunctionInterruptSimulation/FunctionInterruptSimulation.cpp, include/etl/algorithm.h, include/etl/basic_string.h, include/etl/bit_stream.h, include/etl/byte_stream.h, include/etl/fsm.h, include/etl/generators/fsm_generator.h, include/etl/generators/type_traits_generator.h, include/etl/private/ivectorpointer.h, include/etl/private/variant_variadic.h, include/etl/span.h, include/etl/to_arithmetic.h, include/etl/type_traits.h, include/etl/unordered_map.h, include/etl/unordered_multimap.h, include/etl/unordered_multiset.h, include/etl/unordered_set.h, support/Release notes.txt, test/test_multimap.cpp, test/test_multiset.cpp
Utilized a spell checking tool to identify and correct spelling throughout all files in the code base.
=> etl: apply code spell check across entire code base

include/etl/private/variant_variadic.h, test/test_variant_variadic.cpp
Hi,
It seems variant_varadic still contains valid type_id when default constructed, 
initializing to `variant_npos` should resolve the issue.
Regards,
Manuel
=> variant varadic default constructed state

arduino/library-arduino.json, arduino/library-arduino.properties
this is to fix the issue in the arduino repo
https://github.com/ETLCPP/etl-arduino/issues/4
for this to take effect, a git version tag must be pointing to a commit with the fixed name
after the tag is set, the status of its registration by arduino's tools can be checked in the following link:
https://downloads.arduino.cc/libraries/logs/github.com/ETLCPP/etl-arduino/
according to the documentation, the status page is [updated every hour](https://github.com/arduino/library-registry/blob/main/FAQ.md#what-are-the-requirements-for-a-library-to-be-added-to-library-manager)
=> Fixed names according to arduino's guidlines

include/etl/basic_format_spec.h
This pull request introduces a possible fix for the issue #848 by adding the missing initializers.
=> fix(string_stream): add missing initializations of const format specifiers

include/etl/memory.h, test/test_memory.cpp
The assertion in `reset()`: `p_ != p` is triggered by the unconditional `reset(nullptr)` when `unique_ptr` already is set to `nullptr`.
=> fix(unique_ptr): assigning nullptr to a null unique_ptr causes an assert

include/etl/type_def.h, test/test_type_def.cpp
For https://github.com/ETLCPP/etl/issues/838 and https://github.com/ETLCPP/etl/issues/844, added the ability to make constexpr strong types.
=> Implement Constexpr Strong Typedef

include/etl/limits.h, include/etl/random.h
By removing `etl/` from include paths (in `#include` statements), the path to the directory `include/` doesn't need to be provided to the preprocessor as an include path if the files in `include/etl/` are included by other means. This has no disadvantages.
Actually the form `#include "..."` is intended to be used for relative paths in the first place.
This is relevant if one wants to include the source files from `include/etl` only indirectly.
For example we use special generated header files which wrap the include statement of the vanilla header files with diagnostic commands. Those commands disable some compiler diagnostics for ETL's files and re-enable them after the file inclusion. Wrapper files are generated for every non-private header file. We provide the directory with the wrapper …
=> Make include paths to private files relative.

include/etl/exception.h
The documentation comment for `exception::line_number()` in `include/etl/exception.h` states falsely that the return type for the function is a `const char*`. It should state that the return type is `numeric_type`, which is an `int`. So change the documentation comment to reflect that the return type is an `int`.
I know that this is a small issue but when I'm setting up error handling for _ETL_ it just irks me to have my IDE report false data.
=> Fix doc comment for exception::line_number()

include/etl/platform.h, include/etl/private/diagnostic_cxx_20_compat_push.h
=> fix c++20-compat false positive

include/etl/pool.h
The documentation comment for `pool::allocate()` in `include/etl/pool.h` states that the default constructor is to be called, while [according to the documentation](https://www.etlcpp.com/pool.html) and to the code (including the documentation comment for `generic_pool::allocate()`) it is not true.
=> Fix doc comment for pool::allocate()

include/etl/memory.h, include/etl/nullptr.h, include/etl/private/addressof.h
Well, the title is self-explanatory. This is a tiny change anyway, and the code is basically what's proposed in #922.
Edit: As of this moment, I changed the pre-C++11 code from an enum into a  custom class
=> Add an etl::nullptr_t type to <etl/nullptr.h>

include/etl/expected.h, test/test_expected.cpp
Forgot partial specialisation of etl::expected.
Additionally, fixed a small bug in a comparison operator.
=> Fix missing partial specialisation equal operators

include/etl/expected.h, test/test_expected.cpp
Only the implementation for unexpected was there. Therefore, I added the implementations for expected and the corresponding partial specialization.
=> Add missing swap implementations for expected

test/run-tests.sh
- Fix ordering of parameters in help info
- Change spaces to tabs in indentation of methods (unique usage of indentation)
- Fix check for number of parameters to avoid empty string as default parameter value
=> Fix run-tests.sh script

include/etl/pool.h, include/etl/vector.h, test/test_vector.cpp
Superfluous curly braces removed
=> Fix issue #931

include/etl/pool.h, include/etl/profiles/determine_compiler.h
When Wundef is passed to GCC, the preprocessor will complain that `__AVR__` is not defined and thus it has to default it to zero. A simple fix is to check if it's defined and use short-circuiting logic to then check the value
=> Fixes compiler detection with Wundef

include/etl/integral_limits.h
This PR is supposed to bring support for compiling ETL using the -mlarge flag for MSP430 devices. The flag results in using 20 bit pointers instread of 16 bit. This allows for accessing more memory and creating larger program. This Fixes #913
=> added 20 bit integral limits

include/etl/platform.h
Fixes the issue reported here: https://github.com/ETLCPP/etl/issues/937
=> fix: determine legacy variant after determining compiler version

include/etl/histogram.h, test/test_histogram.cpp
This PR fixes the histogram indexing issue when the start index is not zero. The unit test was previously passing because it didn't account for non-zero start index too (seems like a copy-paste of zero offset unit test).
=> Fix histogram indexing when accessed via operator[]

include/etl/base64.h, include/etl/base64_decoder.h, include/etl/base64_encoder.h, include/etl/intrusive_forward_list.h, include/etl/intrusive_list.h
Analog to #879 
By removing `etl/` from include paths (in `#include` statements), the path to the directory `include/` doesn't need to be provided to the preprocessor as an include path if the files in `include/etl/` are included by other means. This has no disadvantages.
Actually the form `#include "..."` is intended to be used for relative paths in the first place.
This is relevant if one wants to include the source files from `include/etl` only indirectly.
For example we use special generated header files which wrap the include statement of the vanilla header files with diagnostic commands. Those commands disable some compiler diagnostics for ETL's files and re-enable them after the file inclusion. Wrapper files are generated for every non-private header file. We provide the directory …
=> Make include paths to private files relative

include/etl/profiles/determine_compiler_language_support.h
From here: https://godbolt.org/z/n967rrMGY you can see that using GCC 10 and compiling with -stdc++=20 that __cplusplus evaluates to 201709. Switching to GCC 11, it evaluates to 202002.
This was problematic in our build as ETL_CPP20_SUPPORTED was not being detected correctly and we were having issues with redefinition of char8_t. Tried to workaround by setting ETL_NO_SMALL_CHAR_SUPPORT=0, however parts of our build use -stdc++=17 which would then fail with this flag due to missing definition of char8_t.
=> For GCC10, check __cplusplus >= 201709 for c++20 support

include/etl/circular_buffer.h
Fixes a build error in `icircular_buffer::iterator` and `icircular_buffer::const_iterator` related to `pbuffer`.
=> Fix build error 

include/etl/private/delegate_cpp03.h, include/etl/private/delegate_cpp11.h, include/etl/type_traits.h
Original problem, how to reproduce:
```
#include <etl/delegate.h>
namespace ctx {
struct os {};
struct any {
any() = default;
any(os) {}
};
} // namespace ctx
struct Test {
etl::delegate<void(ctx::os)> GetCb() {
return etl::delegate<void(ctx::any)>::create<Test,
&Test::CbAnyCtx>(
*this);
}
private:
void CbAnyCtx(ctx::any ctx) {}
};
int main() {
Test().GetCb()(ctx::os{});
etl::delegate<void(void)> f = []() {};
return 0;
}
```
This compiles and does not look suspicious at the first glance but results in a segmentation fault at runtime.
What happens here:
1) A delegate is created `etl::delegate<void(ctx::any ctx)>::create<Test, &Test::CbAnyCtx>(*this);`
2) But we need a etl::delegate<void(ctx::os ctx)>, the compiler selects the constructor from `const TLambda&`.
3) Note that …
=> etl/delegate: fix accident creation of a delegate to an rvalue delegate when copying/assigning from delegate with mismatching signature

README.md, include/etl/span.h, test/test_span_dynamic_extent.cpp, test/test_span_fixed_extent.cpp
std span is getting the `at` method in c++ 26. https://en.cppreference.com/w/cpp/container/span/at
This is adding the equivalent to etl span.
=> Add at method to span

CONTRIBUTING.md, README.md
- Apply instructions for pull requests from Slack to new CONTRIBUTING guideline file.  
I copied the [message in Slack](https://etlcpp.slack.com/archives/C7SJ45VFB/p1729596737002559) from @jwellbelove into a new file for [contributing guidelines](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors). This way a starting point for potential contributors is delivered next to the source code.
- Added hint for the starting point for contributing commits.  
I derived this rule from https://github.com/ETLCPP/etl/issues/802#issuecomment-2323530862
=> Added basic guidelines for contributing code

test/test_bit_stream.cpp, test/test_bit_stream_reader_big_endian.cpp, test/test_bresenham_line.cpp, test/test_correlation.cpp, test/test_covariance.cpp, test/test_rms.cpp
there are few build and test failures on arm64 platform with "narrowing conversion" due to char implementation differences between differnet platforms and gcc versions. This patch is to replace char with explicit datatype that works across all the platforms.
=> fix build and test failures on arm64 linux platform

include/etl/platform.h, include/etl/unaligned_type.h
This way, unaligned_types like etl::be_uint32_t can be used in places where POD types are expected.
=> Packed unaligned_type

include/etl/span.h, test/test_span_fixed_extent.cpp
Since 0-sized spans are allowed, they should report their empty() property as true.
This makes it consistent with the dynamic extent span and the size() property.
=> Fix fixed extent span empty()

test/test_bit_stream.cpp, test/test_bit_stream_reader_big_endian.cpp, test/test_bit_stream_reader_little_endian.cpp, test/test_bresenham_line.cpp, test/test_correlation.cpp, test/test_covariance.cpp, test/test_rms.cpp
On arm64, char is unsigned.
That's why etlcpp tests don't compile on arm64, see e.g. https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1091157
This pull request fixes the issue by making chars explicitly signed where necessary. Tested on Debian sid arm64.
=> Fix arm64 signed char

cmake/helpers.cmake
Followed the approach recommended in #968. Since this is only used in one spot, I didn't bother doing anything more elaborate than just replacing the `PROJECT_IS_TOP_LEVEL` with `CMAKE_CURRENT_LIST_DIR STREQUAL PROJECT_SOURCE_DIR`.
=> #968 Swap PROJECT_IS_TOP_LEVEL called before project()

include/etl/signal.h, test/CMakeLists.txt, test/test_signal.cpp
Initial implementation of signal for https://github.com/ETLCPP/etl/issues/666
I implemented something very similar to this on other software and thought this would be useful for this project.  I would like to use this version over my other implementation.  
Some other things that could be added at some point is being able to pass in an aggregator or some kind of module that can act on all the signals (think sumnation, product, etc).
=> Implement Signal

include/etl/callback_timer_deferred_locked.h, include/etl/callback_timer_locked.h, test/CMakeLists.txt, test/test_callback_timer_deferred_locked.cpp
to address https://github.com/ETLCPP/etl/issues/952
=> Implements deferred callback timer with optional priority

include/etl/span.h, test/test_span_dynamic_extent.cpp, test/test_span_fixed_extent.cpp
Especially without deduction guides in C++14, I typically have the use case of creating a span with long template arguments to the constructor, where they better could be deducted. This PR adds etl::make_span() deducing template arguments.
E.g. `etl::make_span(etldata);`
=> Add etl::make_span()

include/etl/intrusive_forward_list.h, test/test_intrusive_forward_list.cpp
Besides remove() by reference, I provide this remove() by pointer (overload).
Scenario is as follows:
Current remove() by reference uses the comparison operator, comparing actually different instances for equality. In my use case, I have objects in the intrusive_forward_list which don't have a comparison operator defined but I have a pointer to them. This way, I can intentionally remove the actual object from the list pointed to by the pointer.
=> Intrusive forward list add remove by pointer

include/etl/type_list.h, test/CMakeLists.txt, test/test_type_list.cpp
This change adds several traits to type_list.h:
* type_list_contains
* type_list_index_of
* type_list_max_sizeof_type (long name to prevent confusion with type_list_size)
* type_list_max_alignment
Further: test_type_list.cpp including tests for already existing traits.
=> Add traits to type_list

include/etl/span.h
Potential fix for #1050 
I was checking for static checks in the span constructors that should throw compiler errors.  This code compiles using etl::span but the equivalent std::span code will correctly have a compiler error.
```
int arr[5]{};
etl::span span1(arr);
etl::span<int, 10> span2(span1);  //no compile error here despite different extents.  equivalent std span on gcc does have compile error
```
I believe the cause of the problem is that the intended copy constructors are not used because the extents don't match, but it is falling back on the "generic" constructor that does not check the extents.
My workaround is to disable the generic constructor when constructor from another span.  I think there was also an error with the enable_if statement of the second copy constructor that …
=> Potential fix for span construct

include/etl/expected.h
The `const` marked function needs to return a `const` reference to a member variable.
Fixes compiler error: https://godbolt.org/z/7P1hr5Pbn
=> Returning const ref of member from const member function

include/etl/span.h
A small change to the static span constructor from c array to require that `Extent` is equal to `Array_Size`.  std span on gcc also does this same check.
This prevents the following code from compiling:
```
int arr[5]{};
etl::span<int, 10> span1(arr);  //currently no compile error here.  equivalent std span on gcc does have compile error
```
=> Add enable_if restriction for span constructor from c array

include/etl/alignment.h, test/test_alignment.cpp
I have a recurring use case of globally allocated class instances that I need to explicitly construct in a more defined order than implicit construction of global C++ objects can offer.
Therefore, I have a convenience wrapper etl::typed_storage for aligned_storage_as for instantiating an object explicitly at a defined time.
Previously, I tried with etl::optional<T>, which basically supports the same interface I need, but I can't use this one because it always references ~T. But I want the compiler to optimize away the unneeded dtors because the global objects won't get destroyed anyway until power-off in many embedded scenarios.
(You can still explicitly destroy() if needed.)
=> Alignment typed storage

include/etl/basic_string.h
when building without ETL_HAS_STRING_CLEAR_AFTER_USE
Fixes: https://github.com/ETLCPP/etl/issues/1064
=> fix missing is_secure function

zephyr/module.yml
The Zephyr build system requires that modules have a `module.yml` file to specify where the module cmake and kconfig files are located.  These can also be explicitly set as "external" meaning that they do not exist within the module tree, itself. 
These build file can still be specified elsewhere via cmake variables, explained more in-depth here: https://docs.zephyrproject.org/latest/develop/modules.html#modules-module-ext-root This change makes it such that ETL can be included more easily in zephyr projects running on embedded systems. 
A similar change can be observed in the public nanopb repository, where the repo only requires its own `zephyr/module.yml` file to be found by the zephyr build system, but the kconfig and cmake additions can exist outside of the library repository. …
=> Add Zephyr build system module.yml

zephyr/CMakeLists.txt, zephyr/Kconfig, zephyr/module.yml
This will allow ETL to be included via west in a zephyr build without any additional wrappers or external kconfigs.
All files for zephyr support will be contained within the `<etl_root>/zephyr/` directory so as not to clutter the root of the project. 
`add_subdirectory_ifdef()` and `zephyr_link_interface_ifdef()` are functions added by zephyr's cmake extensions. Since this cmake file will only ever be called when building for zephyr, these functions will always be provided by the build system. They will also not impact any builds aside from zephyr builds, as these files will be ignored by other build systems. 
In `zephyr/module.yml`, the "cmake:" and "kconfig:" fields are paths relative to the root of the project that instructs the zephyr build system where to find the relevant …
=> Add full West support for ETL in Zephyr builds

CMakeLists.txt, cmake/GetGitRevisionDescription.cmake, cmake/helpers.cmake
Just add 'etl_' prefix to the cmake helper functions to avoid function overriding like described in #1060.
Also remove unused functions in GetGitRevisionDescription (this added as a separate commit and may be revoked if needed).
closes #1060
=> Fix cmake helper functions collision

include/etl/circular_buffer.h, test/test_circular_buffer_external_buffer.cpp
This change adds an overload for circular_buffer_ext's swap() for rvalue references and a corresponding test.
Closes #1068
=> Add swap(circular_buffer_ext&&) (#1068)

include/etl/span.h, test/test_span_dynamic_extent.cpp
I have a typical use case of removing initial values from a span, e.g. when analysing a header in a protocol, returning the value(s) and then removing it.
Therefore, I added the trim() method to etl::span(), one for returning and removing an initial single value of a specified type from the span, and another overload for returning and removing a whole initial span from the original span.
This PR is intentionally set up based on the development branch instead of the master branch since it builds upon changes not yet available in master, e.g. advance().
=> Add take() to etl::span

include/etl/ipool.h, test/test_pool.cpp
I have the use case of iterating over allocated chunks in pools. Therefore adding the respective iterators.
=> Added iterator and const_iterator to etl::ipool

include/etl/bip_buffer_spsc_atomic.h
The bug happens because  `psize` is set to `numeric_limits<size_type>::max()`  so the code path in get_write_reserve has numeric overflow and won't update `psize`.
The following sequence reproduces the issue:
```cpp
#include <format>
#include <iostream>
#include <etl/bip_buffer_spsc_atomic.h>
int main()
{
etl::bip_buffer_spsc_atomic<uint8_t, 256> buf;
auto b1 = buf.write_reserve_optimal();
assert(b1.size() == 256);
buf.write_commit(b1.first(256));
auto b2 = buf.read_reserve();
assert(b2.size() == 256);
auto b3 = buf.write_reserve_optimal();
assert(b3.size() == 0);
buf.read_commit(b2.first(17));
auto b4 = buf.read_reserve();
assert(b4.size() == 239);
auto b5 = buf.write_reserve_optimal();
assert(b5.size() == 16);
buf.write_commit(b5.first(16));
buf.read_commit(b4.first(10));
auto b6 = …
```
=> Fix numeric overflow in bip buffer's get_write_reserve

include/etl/profiles/determine_compiler_language_support.h, test/test_etl_traits.cpp
Currently, C++23 needs to be handled as a special case in etl_profile.h for ETL_CPP23_SUPPORTED.
This PR detects it via determine_compiler_language_support.h as for the other C++ versions.
=> Add detection of C++23

include/etl/basic_string.h
Newly added usage of wcslen() broke application code. Include wchar.h also.
=> Add missing header wchar.h for usage of wcslen()

zephyr/CMakeLists.txt, zephyr/Kconfig, zephyr/module.yml
The file `zephyr/module.yml` was mangled in aa0d8b322ccfa191bab57ae30b4cf7ba127a6384, making it generate errors when used as a Zephyr module.
This PR fixes the mangling and adds options to `Kconfig` to allow users to configure ETL functionality in Zephyr projects.
=> Fix West support and add ETL configuration options to Kconfig

include/etl/tuple.h
When the move ctors of etl::tuple are in use, typical compile error is:
```
include/etl/tuple.h:336:19: error: no matching function for call to 'forward'
: base_type(etl::forward<tuple<UHead, UTail...>>(other.get_base()))
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../include/etl/utility.h:63:17: note: candidate function template not viable: cannot bind base class object of type 'etl::tuple<unsigned long, unsigned int, double>::base_type' (aka 'tuple<unsigned int, double>') to derived class reference 'typename etl::remove_reference<tuple<unsigned long, unsigned int, double>>::type &' (aka 'etl::tuple<unsigned long, unsigned int, double> &') for 1st argument
constexpr T&& forward(typename etl::remove_reference<T>::type& t) ETL_NOEXCEPT
^
../../include/etl/utility.h:69:17: note: candidate …
```
=> Fix forward in tuple ctor

include/etl/limits.h
In C++23, std::float_denorm_style is deprecated. This leads to warnings, and in case of -Werror, to errors.
=> Ignore deprecation of std::float_denorm_style

include/etl/binary.h, include/etl/profiles/determine_compiler_language_support.h
When clang 17 is in use, and in -std=c++23 mode, it does not support std::byteswap even when standards expects it.
Therefore, detect availability of std::byteswap via macros.
=> Use std::byteswap only if available 

include/etl/tuple.h
When using clang 19, tuple defines tuple_size even though tuple_size is already defined via other headers from ETL. Especially, limits.h needs math.h which in this case defines the tuple_size base template.
This PR conditionally defines the base template depending on the clang version.
=> Fix build of tuple on clang >= 19

include/etl/crc.h, include/etl/crc8_nrsc5.h, include/etl/private/crc_parameters.h, test/CMakeLists.txt, test/test_crc8_nrsc5.cpp
Adds support for the CRC8-NRSC5 algorithm, from [https://crccalc.com](https://crccalc.com).
1) Added the algorithm parameters to `crc_parameters.h`
2) Added header file for the new algorithm, also include it in `crc.h`
3) Added tests based on existing algorithms.
Built & ran tests locally (they passed), hopefully I didn't miss anything else.
=> Add support for CRC8-NRSC5

zephyr/CMakeLists.txt
zephyr_link_interface() does not work as intended because the implementation in zephyr/cmake/modules/extensions.cmake:
function(zephyr_link_interface interface)
target_link_libraries(${interface} INTERFACE zephyr_interface)
endfunction()
is backwards, i.e., target_link_libraries(etl INTERFACE zephyr_interface) vs. target_link_libraries(zephyr_interface INTERFACE etl).
The workaround results in the following CMake code being executed:
target_link_libraries(zephyr_interface INTERFACE etl::etl)
=> Workaround for link libraries call on Zephyr platform

include/etl/intrusive_links.h, test/test_intrusive_links.cpp, test/test_intrusive_list.cpp
According to the [documentation](https://www.etlcpp.com/intrusive_links.html) `void etl::unlink(first, last)` for biderectional links should keep `first`/`last` linked to each other.
But the `last` node is actually cleared up (IMO by mistake).
As a result you can still traverse from `first` to `last` but not vice versa.
The bug also affects `intrusive_list::splice` method which uses erronous `unlink` 
The bug repoduced by...
- correcting `test_unlink_range_bidirectional_link` unit test according to the documentation - now this test fails detecting broken `last.etl_previous`.
- enhancing `test_intrusive_list::test_splice_range_self` unit test to verify also `etl_previous` links after splicing lists - now unit test crashes (b/c reversed list can't be traversed anymore for the same reason). …
=> Fix bug in the `void etl::unlink(first, last)` for bidirectional links.

include/etl/platform.h
When exceptions are disabled in IAR 8.x, the keyword `noexcept` in any form will cause a build error.
Adding back in the conditional support for the `noexcept` keyword based on the etl_profile settings.
=> Added conditional support of noexcept to fix IAR support

include/etl/private/variant_variadic.h
The documentation regarding holding invalid value is incorrect and misleading now. Changing the docs of the default constructor and `valueless_by_exception` in this PR.
=> fix variant_variadic documentation

include/etl/fsm.h, include/etl/hfsm.h, test/CMakeLists.txt, test/test_hfsm_transition_on_enter.cpp
This adds the capability for the HFSM to transition while entering any state (just like with the FSM).  If a parent state signifies a transition before the child is entered, the transition will take place from the parent without entering the child state.
This also add the ability for a self-transition in the FSM to transition on enter.
=> Added support for transitions on state enter for HFSM
