imap.h, iset.h, set.h, set_base.h, test/test_deque.cpp, test/test_map.cpp, test/test_pool.cpp, test/test_set.cpp, test/test_variant.cpp, test/vs2013/etl.vcxproj
Fixed missing const for key in etl::map
Fixed upper_bound and lower_bound implementations
Added AVL balance to etl:map
Added etl:set
=> fix missing const for etl:map

fnv_1.h, imap.h, imultimap.h, imultiset.h, ipriority_queue.h, iqueue.h, map_base.h, multimap.h, multiset.h, priority_queue.h, priority_queue_base.h, set_base.h, test/test_map.cpp, test/test_multimap.cpp, test/test_multiset.cpp, test/test_priority_queue.cpp, test/vs2013/etl.vcxproj, test/vs2013/etl.vcxproj.filters
It is done, multimap and multiset are now implemented.
=> Added multimap/multiset containers

enum_type.h
not certain if this goes to master or development branch.
=> Enum type - fix doc to_string references

src/iflat_map.h
=> Removed incorrect methods from etl::iflat_map::const_iterator class

CMakeLists.txt
The 14.0 release removed all cpp files
=> Fix CMake build by converting etl to a INTERFACE library

include/etl/scheduler.h
=> Fix compile error in scheduler.h

include/etl/function.h, test/test_function.cpp
Change-Id: Id70a05ab1bfdb95499a3c6622379c8bb639f5f40
=> function.h add const to operator ()

conanfile.py
I've created a basic [Conan](https://conan.io) package for the project, which packages all the header files. Possibly this recipe should be extended with the ETL profiles, but I'm just getting started with ETL and I'm still wrapping my head around this library. 
Once stable, the recipe can be uploaded to conan-center so that is globally available for other Conan users.
=> Conan recipe

include/etl/profiles/etl_profile.h
MSVC code analyzer picked this up. Compiling works just fine.
Created following error with PROFILE_CUSTOM
https://docs.microsoft.com/en-us/cpp/error-messages/compiler-errors-1/fatal-error-c1017?view=vs-2019
=> Fix profile header.

Doxyfile
Hi, I was browsing the source code and try to generate Doxygen docs when I noticed that there are a couple of values that are hardcoded, resulting in the things not working. I changed a couple of Doxygen config so it works and looks nicer.
=> Updated doxygen file

examples/platformio/.gitignore, examples/platformio/.vscode/extensions.json, examples/platformio/README.md, examples/platformio/include/etl_profile.h, examples/platformio/platformio.ini, examples/platformio/src/main.cpp
=> Add platformio demo

include/etl/map.h, include/etl/set.h, test/test_map.cpp, test/test_multimap.cpp, test/test_multiset.cpp, test/test_set.cpp
Fixes for set/map::lower_bound (+tests)
=> br test set lowerbound

include/etl/memory.h
=> Added assert.h include into memory.h. assert are used by unique_ptr.

include/etl/stl/alternate/algorithm.h
Follows the example implementation on [1].
[1] https://en.cppreference.com/w/cpp/algorithm/reverse
=> Add NO_STL std::reverse implementation

include/etl/crc16_ccitt.h
Added option of crc16 ccitt_xmodem standart. (#171)
=> Added option of crc16 ccitt_xmodem standart

include/etl/type_traits.h
https://etlcpp.slack.com/archives/C7SJ45VFB/p1584524391072000
https://etlcpp.slack.com/archives/C7SJ45VFB/p1584524913072900
=> Added cpp11 non supported fixes

include/etl/utility.h
If you want me to fix the tests too, please tell me which file it is in  
I have yet to get into the way tests are run in this project
=> Made template compatible with cpp11

include/etl/mutex/mutex_freertos.h
Here is my shot at implementing etl::mutex for FreeRTOS
=> FreeRTOS implementation of etl::mutex

include/etl/nullptr.h, include/etl/string_view.h, support/Release notes.txt
default type and nullptr == and !=
=> Two cpp98 fixes

.gitignore, meson.build
Hi John,
I've added a Meson build system definition for this project, so I can properly use it as a Meson subproject. 
I will commit to maintaining these build rules on an ongoing basis.
=> Meson build rules

include/etl/flat_map.h, include/etl/flat_multimap.h, include/etl/flat_multiset.h, include/etl/flat_set.h
Just some typos I found. I also added some more documentation for flat map from the website. 
Maybe I will do that for the other files as well..
=> WIP: code doc fixes

.github/workflows/main.yml
Build an run the tests on Ubuntu 18.04
=> Added simple version of Github actions file.

include/etl/limits.h
=> Adding ETL_NO_HUGE_VAL_SUPPORT 

include/etl/frame_check_sequence.h, include/etl/jenkins.h
make getter methods of etl::frame_check_sequence const
=> Fcs make getter const

include/etl/forward_list.h, include/etl/indirect_vector.h, include/etl/intrusive_forward_list.h, include/etl/intrusive_list.h, include/etl/list.h, include/etl/map.h, include/etl/multimap.h, include/etl/multiset.h, include/etl/set.h, include/etl/unordered_map.h, include/etl/unordered_multimap.h, include/etl/unordered_multiset.h, include/etl/unordered_set.h
The default assignment operator in C++ shall return a reference to *this.
=> let default assignment operator return a reference to itself

README.md, arduino/create_arduino_library.py, arduino_examples/Example_0_import_etl/Example_0_import_etl.ino, arduino_examples/Vector_Examples/Example_Vector_1_simple_use/Example_Vector_1_simple_use.ino
- update the etl to etl-arduino to push the examples
- add a couple of simple arduino examples
=> add a couple of arduino examples

include/etl/bip_buffer_spsc_atomic.h, test/CMakeLists.txt, test/codeblocks/ETL.cbp, test/test_bip_buffer_spsc_atomic.cpp, test/vs2019/etl.vcxproj, test/vs2019/etl.vcxproj.filters
This is a clean and feature complete commit of the previously submitted version (#330), which in turn can be ignored.
=> introduce bip buffer spsc atomic

include/etl/list.h, test/test_list.cpp, test/test_list_shared_pool.cpp
Also fixing some test asserts related to etl::list.
=> Fix list insert and assign errors

include/etl/forward_list.h, test/test_forward_list.cpp
Assignent and insert_after of count and values of same types has to work
=> Fix compile error insert/assign two same types non-iterator

include/etl/bitset.h
=> Fixed bug where invert changed bits over the TOP_MASK

include/etl/private/variant_legacy.h
=> Fix initialisation order

include/etl/private/bitset_new.h, test/test_bitset_legacy.cpp, test/test_bitset_new_default_element_type.cpp, test/test_bitset_new_ext_default_element_type.cpp
=> fix bug in find_next of (new) bitset class

CMakeLists.txt
Avoids some initialization of C compiler, this is a pure C++ project
=> No need to initialize the C-compiler, small speed improvement

include/etl/deque.h, include/etl/forward_list.h, include/etl/indirect_vector.h, include/etl/list.h, include/etl/optional.h, include/etl/vector.h, test/test_deque.cpp, test/test_forward_list.cpp, test/test_indirect_vector.cpp, test/test_list.cpp, test/test_optional.cpp, test/test_vector.cpp
=> emplace member functions return reference to emplaced value

include/etl/compare.h, test/test_compare.cpp
=> Revert "feature/add utils compare equality operator"

include/etl/expected.h, test/test_expected.cpp
=> Fix issue #923 equality operator for class expected

CMakeLists.txt
=> Restore CMake < 3.14 compatibility
